### PR TITLE
Updated zio-http and http4s-zio2 with performance optimization 

### PR DESCRIPTION
**Pull request by rohanverma94**
### For http4s-zio2-
- Rearranged some code for a better memory profile
- Added static JSON as a response

### For zio-http -
- Included optimization to endpoints by @tusharmath .
- Added JSON using the same optimization.
- For benchmarking purposes, disabled Leak detection & flow control.
- Reorganized & modified the code to include constructs for unforeseen benchmarking scenarios.
- It's better to use every available zio-http feature if the response time can be optimized given the subjectivity of the benchmark scenarios.

### Both http4s-zio2 and zio-http have been compiled and tested on
- Amazon Corretto JDK 11 & 19 with Shenandoah GC.
- Azul JDK 11 & 19 with Shenandoah GC and Zing/C4 GC.
- Need more scenarios where Zing/C4 GC can swing into action, as Azul JDKs are optimized to provide a low memory profile and hence don't really reclaim the expired allocations as there were no allocations above the threshold to reclaim.

### CODE REVIEW

**Comment by gcnyin** [comment]
The purpose of this project is to simulate the real-world application behavior, so it doesn't encourage too much optimization which not happen in real-world. The others submodules are also following this principle. It just used the out-of-box functions.

**Comment by gcnyin** [comment]
Actually, the garbage collector is not vital for this simple test. The circumstance is too simple to see the differences between these gc

**Comment by rohanverma94** [comment]
Initially I also thought that too much optimization to specific cases is not a good precedent for most out-of-box usage patterns. However, since optimization is too basic given that it's just returning a ``plaintext``, it's not too bad  to have those. Moreover new code structure allows the inclusion and exclusion of those optimization in a more composable manner.

Regarding GC, I tested keeping in mind that any change in application design patterns in future will affect the performance of the application. IMO switching the garbage collectors can give insights on several hotpaths in implementation. I chose Shenandoah & Zing because both are low-pause GC, but contrastingly different in how they handle memory.

I made these changes citing more substantial benchmarks like handling of the "database and streams"

**Comment by rohanverma94** [comment]
> The purpose of this project is to simulate the real-world application behavior, so it doesn't encourage too much optimization which not happen in real-world. The others submodules are also following this principle. It just used the out-of-box functions.

Initially I also thought that too much optimization to specific cases is not a good precedent for most out-of-box usage patterns. However, since optimization is too basic given that it's just returning a plaintext, it's not too bad to have those. Moreover new code structure allows the inclusion and exclusion of those optimization in a more composable manner.

Regarding GC, I tested keeping in mind that any change in application design patterns in future will affect the performance of the application. IMO switching the garbage collectors can give insights on several hotpaths in implementation. I chose Shenandoah & Zing because both are low-pause GC, but contrastingly different in how they handle memory.

I made these changes citing more substantial benchmarks like handling of the "database and streams"

**Pull request closed without merging**
