### PR TITLE
I added Zio2 based http4s server, but results are quite depressive...

### PR DESCRIPTION
**Pull request by rohanverma94**
This is based on Zio2 and Cats Effect 3 interop library. Following are the results with Zio2 http4s server -

```
wrk -t2 -c100 -d10s "http://0.0.0.0:8080"

Running 10s test @ http://0.0.0.0:8080
  2 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    53.22ms  196.58ms   1.99s    95.58%
    Req/Sec     2.77k     1.55k    5.27k    54.64%
  53529 requests in 10.03s, 7.86MB read
  Socket errors: connect 0, read 0, write 0, timeout 46
Requests/sec:   5336.39
Transfer/sec:    802.54KB
```
The performance is totally regressive once zio spawns 220 threads, which calls for more optimization. While a http4s server based on Cats Effect 3 with only 64 threads produces the best results. Need to research about regression.

### CODE REVIEW

**Comment by gcnyin** [comment]
You need to add `zio-http4s-benchmark` at the latest line.

```scala
lazy val root = (project in file("."))
  .settings(
    name := "scala-http-benchmark",
    organization := "com.github.gcnyin",
    version := projectVersion,
    scalaVersion := "2.13.8"
  )
  .aggregate(`akka-http-benchmark`, `http4s-benchmark`, `zio-http-benchmark`)
```

**Comment by gcnyin** [comment]
Could you rename `zio-http4s-benchmark` to `http4s-zio-benchmark`? I will change the existing `http4s-benchamrk` to `http4s-ce3-benchmark`.

**Comment by rohanverma94** [comment]
Yes, I will make the changes. Also ``http4s-zio2-benchmark`` would be better

**Comment by rohanverma94** [comment]
Changes done ✅

**Comment by gcnyin** [comment]
Thanks a lot!

**Pull request merged**
